#!/usr/bin/env node
const ANIMATIONS = {
  'fade-in': { css: `@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
.fade-in { animation: fadeIn 300ms ease-out both; }`, duration: '300ms', easing: 'ease-out' },
  'fade-out': { css: `@keyframes fadeOut { from { opacity: 1; } to { opacity: 0; } }
.fade-out { animation: fadeOut 200ms ease-in both; }`, duration: '200ms', easing: 'ease-in' },
  'slide-up': { css: `@keyframes slideUp { from { transform: translateY(16px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
.slide-up { animation: slideUp 300ms ease-out both; }`, duration: '300ms', easing: 'ease-out' },
  'slide-down': { css: `@keyframes slideDown { from { transform: translateY(-16px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
.slide-down { animation: slideDown 300ms ease-out both; }`, duration: '300ms', easing: 'ease-out' },
  'scale-in': { css: `@keyframes scaleIn { from { transform: scale(0.95); opacity: 0; } to { transform: scale(1); opacity: 1; } }
.scale-in { animation: scaleIn 250ms cubic-bezier(0.16,1,0.3,1) both; }`, duration: '250ms', easing: 'cubic-bezier(0.16,1,0.3,1)' },
  'scale-out': { css: `@keyframes scaleOut { from { transform: scale(1); opacity: 1; } to { transform: scale(0.95); opacity: 0; } }
.scale-out { animation: scaleOut 200ms ease-in both; }`, duration: '200ms', easing: 'ease-in' },
  'shake': { css: `@keyframes shake { 0%,100% { transform: translateX(0); } 25% { transform: translateX(-4px); } 75% { transform: translateX(4px); } }
.shake { animation: shake 300ms ease-in-out; }`, duration: '300ms', easing: 'ease-in-out' },
  'pulse': { css: `@keyframes pulse { 0%,100% { transform: scale(1); } 50% { transform: scale(1.05); } }
.pulse { animation: pulse 600ms ease-in-out; }`, duration: '600ms', easing: 'ease-in-out' },
  'spin': { css: `@keyframes spin { to { transform: rotate(360deg); } }
.spin { animation: spin 800ms linear infinite; }`, duration: '800ms', easing: 'linear' },
  'shimmer': { css: `@keyframes shimmer { 0% { background-position: -200% 0; } 100% { background-position: 200% 0; } }
.shimmer { background: linear-gradient(90deg, transparent 25%, rgba(255,255,255,0.1) 50%, transparent 75%); background-size: 200% 100%; animation: shimmer 1.5s linear infinite; }`, duration: '1500ms', easing: 'linear' },
};

const args = process.argv.slice(2);
const name = args[0];
const format = args.includes('--format') ? args[args.indexOf('--format') + 1] : 'css';

if (!name || name === '--list') {
  console.log('\nAvailable animations:\n');
  Object.entries(ANIMATIONS).forEach(([k, v]) => console.log(`  ${k.padEnd(15)} ${v.duration} ${v.easing}`));
  console.log('\nUsage: node generate.js <name|all> [--format css|json]');
  process.exit(0);
}

if (name === 'all') {
  if (format === 'json') {
    console.log(JSON.stringify(ANIMATIONS, null, 2));
  } else {
    console.log('/* Animation Library — Generated by DesignCortex */\n');
    console.log('@media (prefers-reduced-motion: reduce) {');
    console.log('  *, *::before, *::after { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; }');
    console.log('}\n');
    Object.values(ANIMATIONS).forEach(a => console.log(a.css + '\n'));
  }
} else if (ANIMATIONS[name]) {
  console.log(ANIMATIONS[name].css);
} else {
  console.error(`Unknown animation: ${name}. Use --list to see available.`);
}
