#!/usr/bin/env node
const fs = require('fs');

const prompt = process.argv.slice(2).join(' ');
if (!prompt) { console.log('Usage: node generate.js "Redesign the checkout flow for mobile users"'); process.exit(0); }

const brief = `# Design Brief

## Project
${prompt}

## Problem Statement
[Fill in: What specific problem does this solve? Who experiences it? What's the impact of not solving it?]

## Target User
- **Who:** [Specific person in specific context]
- **Context:** [When and where they encounter this problem]
- **Current behavior:** [How they solve it today]

## Success Criteria
- [ ] [Measurable outcome 1]
- [ ] [Measurable outcome 2]
- [ ] [Measurable outcome 3]

## Scope

### In Scope
- [Feature/page/flow 1]
- [Feature/page/flow 2]

### Out of Scope
- [Explicitly excluded item 1]
- [Explicitly excluded item 2]

## Constraints
- **Timeline:** [Deadline]
- **Technical:** [Platform, framework, browser support]
- **Brand:** [Design system, brand guidelines]
- **Accessibility:** WCAG AA minimum

## Design Direction
- **Mood:** [How should it feel?]
- **References:** [Existing products, sites, or patterns to reference]
- **Anti-references:** [What it should NOT look like]

## Open Questions
1. [Question that needs answering before/during design]
2. [Question that needs answering before/during design]

## Key Dates
- Brief finalized: [Date]
- First review: [Date]
- Final delivery: [Date]

---
*Generated by DesignCortex design-brief skill*
`;

const output = process.argv.includes('--output') ? process.argv[process.argv.indexOf('--output') + 1] : null;
if (output) { fs.writeFileSync(output, brief); console.log(`Brief written to ${output}`); }
else console.log(brief);
