'use strict';

// handoff engine. produces a markdown doc designed for the engineer
// receiving a feature, with everything they need: tokens, conventions,
// existing components, where new things should go.

const fs = require('fs');
const path = require('path');
const { walk, readSafe, COMPONENT_EXTENSIONS } = require('./files');

function listComponents(root, manifest) {
  const files = walk(root);
  const components = [];
  for (const file of files) {
    const ext = path.extname(file).toLowerCase();
    if (!COMPONENT_EXTENSIONS.has(ext)) continue;
    const base = path.basename(file, ext);
    if (/^[A-Z]/.test(base)) {
      components.push({ name: base, path: path.relative(root, file), ext });
    }
  }
  components.sort((a, b) => a.name.localeCompare(b.name));
  return components.slice(0, 50);
}

function generateHandoff({ root, manifest, feature }) {
  const tokens = manifest && manifest.tokens || {};
  const palette = (tokens.color && tokens.color.palette) || [];
  const sizes = (tokens.type && tokens.type.fontSizes) || [];
  const grid = (manifest && manifest.rules && manifest.rules.spacingGrid) || 8;
  const motion = tokens.motion || {};
  const components = manifest ? listComponents(root, manifest) : [];

  const stack = manifest && manifest.stack
    ? `${manifest.stack.framework} + ${(manifest.stack.styling || []).join(', ')} (${manifest.stack.language})`
    : 'unknown';

  const paletteRows = palette.slice(0, 8).map(p =>
    `| \`${p.value}\` | ${p.role || 'unknown'} | ${p.count} |`
  ).join('\n') || '| _none_ | | |';

  const sizesList = sizes.slice(0, 8).map(s => `${s.px}px (×${s.count})`).join(', ') || 'none detected';

  const componentsList = components.length > 0
    ? components.slice(0, 25).map(c => `- \`${c.path}\` (${c.name})`).join('\n')
    : '_no components detected_';

  const easings = (motion.easings || []).map(e => `\`${e.value}\``).slice(0, 3).join(', ') || 'none detected';
  const durations = (motion.durations || []).map(d => `${d.ms}ms`).slice(0, 3).join(', ') || 'none detected';

  const featureSlug = feature
    ? feature.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40)
    : 'general';

  return {
    relPath: `.dragoon/handoff/handoff-${featureSlug}.md`,
    content: `# handoff: ${feature || 'general'}

> generated by dragoon. everything the next engineer needs to ship in this codebase.

## stack

**${stack}**

## design tokens

### palette (top 8 by usage)

| color | role | usage |
|-------|------|-------|
${paletteRows}

### type

- font families: ${((tokens.type && tokens.type.fontFamilies) || []).map(f => f.value).join(', ') || 'none detected'}
- type ratio: ${(tokens.type && tokens.type.scaleName) || 'none'} (${(tokens.type && tokens.type.inferredScaleRatio) || 'n/a'})
- detected sizes: ${sizesList}

### spacing

- base grid: **${grid}px**
- distinct values used: ${((tokens.spacing && tokens.spacing.values) || []).length}

### radius

- detected variants: ${((tokens.radius && tokens.radius.values) || []).map(r => `${r.px}px`).join(', ') || 'none'}

### motion

- durations: ${durations}
- easings: ${easings}

## existing components (sample)

${componentsList}

## conventions

- new components go to \`src/components/\` (or \`--dir\` of \`dragoon component\`)
- new tokens go to \`src/styles/\` (\`tokens.*.{css,js,cjs}\`)
- run \`dragoon scan\` after major design changes to refresh the manifest
- gate every PR with \`dragoon ship\`

## checklist before merging

- [ ] \`dragoon critique --threshold 80\` passes
- [ ] \`dragoon slop --severity high\` is clean
- [ ] \`dragoon review --diff\` shows no high findings
- [ ] new components scaffold-tested with \`dragoon component <Name>\`
- [ ] every new design token added through /typography, /color, /spacing, or /motion

## links

- design tokens: \`src/styles/\`
- manifest: \`dragoon.json\`
- plans: \`.dragoon/plans/\`
- this handoff: \`.dragoon/handoff/\`
`
  };
}

module.exports = { generateHandoff, listComponents };
