'use strict';

// plan engine. generates structured planning docs pre-filled with facts from
// dragoon.json, package.json, and the repo. each plan goes to .dragoon/plans/
// with a predictable filename: plan-{kind}-{slug}-{YYYYMMDD}.md
//
// plans are templates the user (or their agent) fills in. the value is:
//   - consistent structure across the team
//   - codebase-specific facts pre-loaded
//   - the right questions surfaced
//   - blank-page time saved

const path = require('path');
const fs = require('fs');

function slugify(s, max = 40) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, max) || 'untitled';
}

function dateStamp() {
  const d = new Date();
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const day = String(d.getUTCDate()).padStart(2, '0');
  return `${y}${m}${day}`;
}

function readPackageJson(root) {
  const p = path.join(root, 'package.json');
  if (!fs.existsSync(p)) return null;
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch (_e) { return null; }
}

function describeStack(stack) {
  if (!stack) return 'unknown stack';
  return `${stack.framework} + ${(stack.styling || []).join(', ') || 'no styling'} (${stack.language})`;
}

function describeManifest(manifest) {
  if (!manifest) return null;
  const t = manifest.tokens || {};
  return {
    stack: describeStack(manifest.stack),
    grid: t.spacing && t.spacing.inferredGrid ? `${t.spacing.inferredGrid}px (confidence ${t.spacing.gridConfidence})` : 'not detected',
    typeRatio: t.type && t.type.inferredScaleRatio ? `${t.type.scaleName || ''} (${t.type.inferredScaleRatio})` : 'not detected',
    paletteSize: (t.color && t.color.totalDistinct) || 0,
    fontFamilies: ((t.type && t.type.fontFamilies) || []).map(f => f.value).join(', ') || 'none',
    components: (manifest.metrics && manifest.metrics.components && manifest.metrics.components.estimated) || 0,
    files: (manifest.metrics && manifest.metrics.files && manifest.metrics.files.scanned) || 0
  };
}

// ---------- brief ----------

function generateBrief({ idea, manifest, root }) {
  const pkg = readPackageJson(root);
  const projectName = (pkg && pkg.name) || (manifest && manifest.project && manifest.project.name) || path.basename(root);
  const m = describeManifest(manifest);
  const slug = slugify(idea);
  const stamp = dateStamp();
  const stackBlock = m ? `- **stack**: ${m.stack}\n- **components today**: ~${m.components} across ${m.files} files\n- **type system**: ${m.fontFamilies} on ${m.typeRatio}\n- **spacing grid**: ${m.grid}\n- **palette**: ${m.paletteSize} distinct colors` : '_run `dragoon scan` first to load codebase facts here_';
  return {
    relPath: `.dragoon/plans/brief-${slug}-${stamp}.md`,
    content: `# brief: ${idea}

> generated by dragoon ${dateStamp()}. fill in the blanks, then move to /plan-eng and /plan-design

## one-line idea

${idea}

## why now

_what's changed that makes this matter? what's the cost of not doing it?_

## who is this for

_specific user. one persona. not "everyone."_

## what does success look like

_a number you can measure in 30 days. not "users will love it."_

## the smallest version that proves the idea

_what would you ship in a week to test the hypothesis?_

## what could go wrong

_three failure modes. for each, the leading indicator that tells you it's failing._

## codebase context (auto-loaded)

project: **${projectName}**

${stackBlock}

## next steps

- [ ] sharpen this brief with /interrogate (forcing questions)
- [ ] generate engineering plan: \`dragoon plan-eng "${idea}"\`
- [ ] generate design plan: \`dragoon plan-design "${idea}"\`
- [ ] run all three at once: \`dragoon autoplan "${idea}"\`
`
  };
}

// ---------- plan-eng ----------

function generatePlanEng({ idea, manifest, root }) {
  const pkg = readPackageJson(root);
  const m = describeManifest(manifest);
  const slug = slugify(idea);
  const stamp = dateStamp();
  const projectName = (pkg && pkg.name) || (manifest && manifest.project && manifest.project.name) || path.basename(root);

  // extract dependency hints
  const deps = pkg ? Object.keys({ ...pkg.dependencies, ...pkg.devDependencies }) : [];
  const depHints = deps.slice(0, 12).join(', ') || 'no dependencies detected';

  const stackBlock = m ? `**stack**: ${m.stack}` : '_no manifest; run `dragoon scan` for stack-aware suggestions_';

  return {
    relPath: `.dragoon/plans/plan-eng-${slug}-${stamp}.md`,
    content: `# engineering plan: ${idea}

> generated by dragoon ${dateStamp()}

${stackBlock}

## architecture

_how does this fit the existing system? what new modules, services, or boundaries does it introduce?_

### data model

_new tables, types, schemas. include migrations._

### api / interface

_new endpoints, exports, public functions. include shapes._

### state & persistence

_what's in memory, what's in storage, what crosses the network?_

## edge cases

_list at least five. for each, the failure mode and the test that catches it._

1. _empty input_:
2. _maximum size input_:
3. _concurrent calls_:
4. _network failure mid-flight_:
5. _malformed third-party data_:

## test matrix

| layer | what to test | tool |
|-------|--------------|------|
| unit | _pure functions_ | _e.g. node:test, vitest_ |
| integration | _module boundaries_ | _e.g. supertest_ |
| e2e | _critical user paths_ | _e.g. playwright_ |
| performance | _hot paths under load_ | _e.g. autocannon_ |

## existing dependencies (auto-loaded)

${depHints}

## migration / rollout

- [ ] feature flag plan
- [ ] data backfill plan
- [ ] rollback plan
- [ ] observability (logs, metrics, traces) before launch

## review checklist

- [ ] every public function has a test
- [ ] every error path has a test
- [ ] no \`any\` types in new TS code
- [ ] no console.log in shipped code
- [ ] /critique score has not regressed (\`dragoon critique --threshold ${(manifest && manifest.scores && manifest.scores.overall) || 80}\`)

## next steps

- [ ] run \`dragoon plan-design "${idea}"\` to align design plan
- [ ] when both plans are stable, scaffold with \`dragoon component\` and \`dragoon feature\`
`
  };
}

// ---------- plan-design ----------

function generatePlanDesign({ idea, manifest, root }) {
  const m = describeManifest(manifest);
  const slug = slugify(idea);
  const stamp = dateStamp();
  const palette = (manifest && manifest.tokens && manifest.tokens.color && manifest.tokens.color.palette) || [];
  const paletteList = palette.slice(0, 6).map(p => `- \`${p.value}\` (${p.role || 'unknown'})`).join('\n') || '_no palette detected_';
  const constraints = m ? `**must respect**:\n- spacing grid: ${m.grid}\n- type ratio: ${m.typeRatio}\n- font families: ${m.fontFamilies}\n- palette (top 6):\n${paletteList}` : '_run `dragoon scan` to load design constraints_';

  return {
    relPath: `.dragoon/plans/plan-design-${slug}-${stamp}.md`,
    content: `# design plan: ${idea}

> generated by dragoon ${dateStamp()}

## constraints (from dragoon.json)

${constraints}

## the moment that matters

_what's the single visual or interaction the user will remember? describe in one sentence, no jargon._

## screens & flows

_list the screens, with a one-line description each. include empty states, error states, loading states._

1. _entry point_:
2. _success state_:
3. _empty state_:
4. _error state_:
5. _loading state_:

## new tokens needed

_does this require any new design tokens? if so, propose them here as additions to the existing system, not replacements._

- [ ] new colors:
- [ ] new spacing:
- [ ] new motion:
- [ ] new typography:

## accessibility plan

- [ ] keyboard navigation flow
- [ ] focus order
- [ ] screen reader labels
- [ ] color contrast (target: WCAG AA, 4.5:1 for body, 3:1 for large)
- [ ] respects \`prefers-reduced-motion\`

## responsive plan

| breakpoint | what changes |
|------------|--------------|
| mobile (<640) | _layout adaptations_ |
| tablet (640-1024) | _layout adaptations_ |
| desktop (>1024) | _layout adaptations_ |

## review checklist

- [ ] every screen passes \`dragoon critique --threshold 80\`
- [ ] no slop introduced (\`dragoon slop --severity high\`)
- [ ] all new tokens added through /typography, /color, /spacing, or /motion
- [ ] design assets exported and accessible to engineering

## next steps

- [ ] cross-check with the engineering plan (review them together)
- [ ] when stable, scaffold UI with \`dragoon component\`
`
  };
}

module.exports = { generateBrief, generatePlanEng, generatePlanDesign, slugify, dateStamp };
