'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function tryExec(cmd, root) {
  try { return execSync(cmd, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], timeout: 5000 }); }
  catch (_e) { return null; }
}

function dateStamp() {
  const d = new Date();
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}${String(d.getUTCDate()).padStart(2, '0')}`;
}
function isoNow() { return new Date().toISOString(); }

// ---------- /retro ----------
// produces a markdown retro doc with git-derived facts already filled in
// (commits this week, files touched, contributors).

function generateRetro({ root, weeks = 1 }) {
  const since = `${weeks} weeks ago`;
  const commits = tryExec(`git log --since="${since}" --pretty=format:"%h %s" -100`, root);
  const stats = tryExec(`git log --since="${since}" --shortstat --pretty=format:"" -100`, root);
  const authors = tryExec(`git log --since="${since}" --pretty=format:"%an" | sort -u`, root);

  let filesChanged = 0, insertions = 0, deletions = 0;
  if (stats) {
    for (const line of stats.split('\n')) {
      const fc = line.match(/(\d+)\s+files?\s+changed/);
      const ins = line.match(/(\d+)\s+insertions?\(\+\)/);
      const del = line.match(/(\d+)\s+deletions?\(-\)/);
      if (fc) filesChanged += parseInt(fc[1], 10);
      if (ins) insertions += parseInt(ins[1], 10);
      if (del) deletions += parseInt(del[1], 10);
    }
  }
  const commitCount = commits ? commits.trim().split('\n').filter(Boolean).length : 0;
  const authorCount = authors ? authors.trim().split('\n').filter(Boolean).length : 0;

  const stamp = dateStamp();
  return {
    relPath: `.dragoon/retros/retro-${stamp}.md`,
    content: `# retro: week ending ${stamp}

> generated by dragoon. git stats pre-loaded. fill in the rest.

## by the numbers

- commits: **${commitCount}**
- files changed: ${filesChanged}
- lines: +${insertions} -${deletions}
- contributors: ${authorCount}

## what shipped

_concrete things we shipped this week. links to PRs._

-

## what slipped

_what didn't ship that we expected to. why._

-

## what we learned

_one or two things that will change how we work next week._

-

## what to do less of

_a behavior to drop. concrete, observable._

-

## what to do more of

_something that worked, that we want to scale up._

-

## quality trends

_run \`dragoon critique\` and compare to last week's score. is it going up?_

- design score:
- a11y findings:
- slop findings:

## next week

_top three priorities. ranked. don't list five._

1.
2.
3.
`
  };
}

// ---------- /memory ----------
// .dragoon/memory.json is a small key-value store of project-specific facts
// dragoon (and the user) want to remember across sessions.
// commands: list, set, get, remove.

const MEMORY_PATH = '.dragoon/memory.json';

function loadMemory(root) {
  const p = path.join(root, MEMORY_PATH);
  if (!fs.existsSync(p)) return { entries: {}, updatedAt: null };
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch (_e) { return { entries: {}, updatedAt: null }; }
}

function saveMemory(root, mem) {
  // path resolution stays inside root via Patcher contract; here we know our
  // path is a safe constant.
  const p = path.join(root, MEMORY_PATH);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const tmp = p + '.tmp-' + process.pid;
  fs.writeFileSync(tmp, JSON.stringify({ ...mem, updatedAt: isoNow() }, null, 2), 'utf8');
  fs.renameSync(tmp, p);
}

const KEY_RE = /^[a-z][a-z0-9._-]{0,63}$/;
function validKey(k) { return typeof k === 'string' && KEY_RE.test(k); }

// ---------- /benchmark ----------
// snapshots a few measurable codebase facts (file count, total lines, score
// from /critique if a manifest exists) and stores them in
// .dragoon/benchmarks/<date>.json. you can compare snapshots over time.

function captureBenchmark(root) {
  const { walk } = require('./files');
  const { critique } = require('./critique-engine');
  const allFiles = walk(root);
  let totalLines = 0;
  for (const f of allFiles) {
    try { totalLines += fs.readFileSync(f, 'utf8').split('\n').length; }
    catch (_e) { /* skip */ }
  }
  const manifestPath = path.join(root, 'dragoon.json');
  let scores = null;
  if (fs.existsSync(manifestPath)) {
    try {
      const m = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
      scores = critique(m).scores;
    } catch (_e) { /* skip */ }
  }
  return {
    capturedAt: isoNow(),
    files: allFiles.length,
    totalLines,
    scores
  };
}

function compareBenchmarks(prev, cur) {
  if (!prev || !cur) return null;
  const diffs = {
    files: cur.files - prev.files,
    totalLines: cur.totalLines - prev.totalLines
  };
  if (prev.scores && cur.scores) {
    diffs.scores = {};
    for (const k of Object.keys(cur.scores)) {
      diffs.scores[k] = cur.scores[k] - (prev.scores[k] || 0);
    }
  }
  return diffs;
}

module.exports = {
  generateRetro,
  loadMemory, saveMemory, validKey, MEMORY_PATH,
  captureBenchmark, compareBenchmarks
};
