'use strict';

// research engine. NO network calls. produces a template doc the user fills
// in by hand or hands to their agent. zero dep, zero ssrf, zero surprise.

const path = require('path');

function slugify(s, max = 40) {
  return String(s).toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, max) || 'untitled';
}
function dateStamp() {
  const d = new Date();
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}${String(d.getUTCDate()).padStart(2, '0')}`;
}

function generateResearch({ topic }) {
  const slug = slugify(topic);
  const stamp = dateStamp();
  return {
    relPath: `.dragoon/research/research-${slug}-${stamp}.md`,
    content: `# research: ${topic}

> generated by dragoon ${stamp}. fill in each section. dragoon does NOT fetch the web.
> use this template with your agent (or by hand) to organize what you find.

## the question

_what specifically are we trying to learn? not "research X" - "decide whether X solves Y"._

## decision this informs

_what choice does the answer change? if no decision changes either way, do not research._

## existing solutions

| name | what it does | gaps | source |
|------|--------------|------|--------|
| _name_ | _summary_ | _what's missing_ | _url_ |

## key facts

_specific, citable, numerical where possible._

1. _fact + source_:
2. _fact + source_:
3. _fact + source_:

## what experts disagree on

_genuine disagreement points. avoid summarizing - quote and cite._

- _position A (who, source)_: ...
- _position B (who, source)_: ...

## the strongest argument against doing this

_steelman the no-side. if you can't, you don't understand the problem._

## what I'm still uncertain about

_things you'd want a domain expert to weigh in on._

## decision

_after the above is filled in, what does the evidence point to?_

- [ ] do this thing
- [ ] don't do this thing
- [ ] need more information about: _...specific question..._

## next steps

- [ ] turn this into a brief: \`dragoon brief "${topic}"\`
- [ ] if it's clearly worth building, run: \`dragoon autoplan "${topic}"\`
`
  };
}

module.exports = { generateResearch };
