#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { staticPerfScan, summarizeLighthouse, STATIC_RULES } = require('../../../lib/perf-engine');
const { c, header, fmtFinding, fmtFindingsSummary } = require('../../../lib/output');

const HELP = `dragoon perf - static perf hints + optional lighthouse report ingestion

USAGE
  dragoon perf [path] [--lighthouse report.json] [--severity s] [--rules] [--json]

STATIC RULES
  perf-001  large-image (>500KB)                      [medium]
  perf-002  img-missing-dimensions                    [low]
  perf-003  img-without-loading-lazy                  [low]
  perf-004  sync-script-tag                           [medium]

LIGHTHOUSE INGESTION
  Pass --lighthouse with a path to a Lighthouse JSON report (generated by:
    \`npx lighthouse <url> --output json --output-path lh.json\`
  ) and dragoon surfaces failing audits in actionable form.

FLAGS
  --lighthouse <p>  ingest a lighthouse JSON report
  --severity <s>    filter to severity at or above (low|medium|high)
  --rules           list rules and exit
  --json            machine-readable output
  --quiet           only show findings, no summary
  --help, -h        this help

EXIT CODES
  0  no findings
  1  findings present
  2  bad usage
`;

function parseArgs(argv) {
  const args = { _: [], lighthouse: null, severity: 'low', rules: false, json: false, quiet: false, help: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help' || a === '-h') args.help = true;
    else if (a === '--lighthouse') args.lighthouse = argv[++i];
    else if (a === '--severity') args.severity = argv[++i];
    else if (a === '--rules') args.rules = true;
    else if (a === '--json') args.json = true;
    else if (a === '--quiet') args.quiet = true;
    else if (a.startsWith('--')) { console.error(`unknown flag: ${a}`); process.exit(2); }
    else args._.push(a);
  }
  return args;
}

function severityRank(s) { return { low: 0, medium: 1, high: 2 }[s] ?? 0; }

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) { process.stdout.write(HELP); return 0; }
  if (args.rules) {
    for (const r of STATIC_RULES) process.stdout.write(`${r.id}  ${r.name}  [${r.severity}]\n  ${r.description}\n\n`);
    return 0;
  }

  const root = path.resolve(args._[0] || process.cwd());
  if (!fs.existsSync(root)) { console.error(`perf: not found: ${root}`); return 2; }

  const minRank = severityRank(args.severity);
  const findings = staticPerfScan(root).filter(f => severityRank(f.severity) >= minRank);

  let lhSummary = null;
  if (args.lighthouse) {
    if (!fs.existsSync(args.lighthouse)) { console.error(`perf: lighthouse report not found: ${args.lighthouse}`); return 2; }
    let report;
    try { report = JSON.parse(fs.readFileSync(args.lighthouse, 'utf8')); }
    catch (e) { console.error(`perf: invalid lighthouse json: ${e.message}`); return 2; }
    lhSummary = summarizeLighthouse(report);
  }

  if (args.json) {
    process.stdout.write(JSON.stringify({
      root, staticFindings: findings, lighthouse: lhSummary
    }, null, 2) + '\n');
    return findings.length > 0 ? 1 : 0;
  }

  process.stdout.write(header('perf'));

  if (lhSummary) {
    process.stdout.write(`${c.bold}lighthouse${c.reset}\n`);
    const s = lhSummary.scores;
    if (s.performance != null) {
      const col = s.performance >= 90 ? c.green : s.performance >= 50 ? c.yellow : c.red;
      process.stdout.write(`  performance:    ${col}${s.performance}/100${c.reset}\n`);
    }
    if (s.accessibility != null) process.stdout.write(`  accessibility:  ${s.accessibility}/100\n`);
    if (s.bestPractices != null) process.stdout.write(`  best practices: ${s.bestPractices}/100\n`);
    if (s.seo != null) process.stdout.write(`  seo:            ${s.seo}/100\n`);
    if (Object.keys(lhSummary.cwv).length > 0) {
      process.stdout.write(`\n  ${c.gray}core web vitals:${c.reset}\n`);
      for (const [k, v] of Object.entries(lhSummary.cwv)) {
        process.stdout.write(`    ${k.padEnd(5)} ${v}\n`);
      }
    }
    if (lhSummary.failing.length > 0) {
      process.stdout.write(`\n  ${c.gray}top failing audits:${c.reset}\n`);
      for (const a of lhSummary.failing.slice(0, 6)) {
        const savings = a.savingsMs ? ` (${Math.round(a.savingsMs)}ms savings)` : '';
        process.stdout.write(`    ${c.yellow}${a.score}/100${c.reset} ${a.title}${c.gray}${savings}${c.reset}\n`);
      }
    }
    process.stdout.write('\n');
  }

  process.stdout.write(`${c.bold}static findings${c.reset}\n`);
  if (!args.quiet) process.stdout.write(fmtFindingsSummary(findings));
  const byFile = new Map();
  for (const f of findings) {
    if (!byFile.has(f.file)) byFile.set(f.file, []);
    byFile.get(f.file).push(f);
  }
  for (const [, list] of byFile) {
    list.sort((a, b) => a.line - b.line);
    for (const f of list) process.stdout.write(fmtFinding(f));
  }
  return findings.length > 0 ? 1 : 0;
}

process.exit(main());
